# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_pb/manager_grpc_server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!grpc_pb/manager_grpc_server.proto\x12\x13manager_grpc_server\"T\n\x18UpdateAgentStatusRequest\x12\x10\n\x08\x61gent_ip\x18\x01 \x01(\t\x12\x12\n\nagent_type\x18\x02 \x01(\t\x12\x12\n\nagent_meta\x18\x03 \x01(\t\"+\n\x19UpdateAgentStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"H\n\x1eGatherInstalledPackagesRequest\x12\x10\n\x08\x61gent_ip\x18\x01 \x01(\t\x12\x14\n\x0c\x61ll_packages\x18\x02 \x01(\t\"1\n\x1fGatherInstalledPackagesResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"C\n\x13RunScaChecksRequest\x12\x10\n\x08\x61gent_ip\x18\x01 \x01(\t\x12\x1a\n\x12sca_checks_results\x18\x02 \x01(\t\"&\n\x14RunScaChecksResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"o\n\x15TasksInterfaceRequest\x12\x10\n\x08req_type\x18\x01 \x01(\t\x12\x10\n\x08\x61gent_id\x18\x02 \x01(\t\x12\x0e\n\x06result\x18\x03 \x01(\t\x12\x0f\n\x07task_id\x18\x04 \x01(\t\x12\x11\n\ttask_code\x18\x05 \x01(\t\"h\n\x16TasksInterfaceResponse\x12\x11\n\ttask_code\x18\x01 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x01(\t\x12\x1c\n\x14task_target_agent_id\x18\x03 \x01(\t\x12\x0f\n\x07task_id\x18\x04 \x01(\t2\xdb\x03\n\nGrpcServer\x12r\n\x11UpdateAgentStatus\x12-.manager_grpc_server.UpdateAgentStatusRequest\x1a..manager_grpc_server.UpdateAgentStatusResponse\x12\x84\x01\n\x17GatherInstalledPackages\x12\x33.manager_grpc_server.GatherInstalledPackagesRequest\x1a\x34.manager_grpc_server.GatherInstalledPackagesResponse\x12\x63\n\x0cRunScaChecks\x12(.manager_grpc_server.RunScaChecksRequest\x1a).manager_grpc_server.RunScaChecksResponse\x12m\n\x0eTasksInterface\x12*.manager_grpc_server.TasksInterfaceRequest\x1a+.manager_grpc_server.TasksInterfaceResponse(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_pb.manager_grpc_server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UPDATEAGENTSTATUSREQUEST._serialized_start=58
  _UPDATEAGENTSTATUSREQUEST._serialized_end=142
  _UPDATEAGENTSTATUSRESPONSE._serialized_start=144
  _UPDATEAGENTSTATUSRESPONSE._serialized_end=187
  _GATHERINSTALLEDPACKAGESREQUEST._serialized_start=189
  _GATHERINSTALLEDPACKAGESREQUEST._serialized_end=261
  _GATHERINSTALLEDPACKAGESRESPONSE._serialized_start=263
  _GATHERINSTALLEDPACKAGESRESPONSE._serialized_end=312
  _RUNSCACHECKSREQUEST._serialized_start=314
  _RUNSCACHECKSREQUEST._serialized_end=381
  _RUNSCACHECKSRESPONSE._serialized_start=383
  _RUNSCACHECKSRESPONSE._serialized_end=421
  _TASKSINTERFACEREQUEST._serialized_start=423
  _TASKSINTERFACEREQUEST._serialized_end=534
  _TASKSINTERFACERESPONSE._serialized_start=536
  _TASKSINTERFACERESPONSE._serialized_end=640
  _GRPCSERVER._serialized_start=643
  _GRPCSERVER._serialized_end=1118
# @@protoc_insertion_point(module_scope)
