# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import manager_grpc_server_pb2 as grpc__pb_dot_manager__grpc__server__pb2


class GrpcServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateAgentStatus = channel.unary_unary(
                '/manager_grpc_server.GrpcServer/UpdateAgentStatus',
                request_serializer=grpc__pb_dot_manager__grpc__server__pb2.UpdateAgentStatusRequest.SerializeToString,
                response_deserializer=grpc__pb_dot_manager__grpc__server__pb2.UpdateAgentStatusResponse.FromString,
                )
        self.GatherInstalledPackages = channel.unary_unary(
                '/manager_grpc_server.GrpcServer/GatherInstalledPackages',
                request_serializer=grpc__pb_dot_manager__grpc__server__pb2.GatherInstalledPackagesRequest.SerializeToString,
                response_deserializer=grpc__pb_dot_manager__grpc__server__pb2.GatherInstalledPackagesResponse.FromString,
                )
        self.RunScaChecks = channel.unary_unary(
                '/manager_grpc_server.GrpcServer/RunScaChecks',
                request_serializer=grpc__pb_dot_manager__grpc__server__pb2.RunScaChecksRequest.SerializeToString,
                response_deserializer=grpc__pb_dot_manager__grpc__server__pb2.RunScaChecksResponse.FromString,
                )
        self.TasksInterface = channel.stream_stream(
                '/manager_grpc_server.GrpcServer/TasksInterface',
                request_serializer=grpc__pb_dot_manager__grpc__server__pb2.TasksInterfaceRequest.SerializeToString,
                response_deserializer=grpc__pb_dot_manager__grpc__server__pb2.TasksInterfaceResponse.FromString,
                )


class GrpcServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdateAgentStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GatherInstalledPackages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunScaChecks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TasksInterface(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GrpcServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateAgentStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAgentStatus,
                    request_deserializer=grpc__pb_dot_manager__grpc__server__pb2.UpdateAgentStatusRequest.FromString,
                    response_serializer=grpc__pb_dot_manager__grpc__server__pb2.UpdateAgentStatusResponse.SerializeToString,
            ),
            'GatherInstalledPackages': grpc.unary_unary_rpc_method_handler(
                    servicer.GatherInstalledPackages,
                    request_deserializer=grpc__pb_dot_manager__grpc__server__pb2.GatherInstalledPackagesRequest.FromString,
                    response_serializer=grpc__pb_dot_manager__grpc__server__pb2.GatherInstalledPackagesResponse.SerializeToString,
            ),
            'RunScaChecks': grpc.unary_unary_rpc_method_handler(
                    servicer.RunScaChecks,
                    request_deserializer=grpc__pb_dot_manager__grpc__server__pb2.RunScaChecksRequest.FromString,
                    response_serializer=grpc__pb_dot_manager__grpc__server__pb2.RunScaChecksResponse.SerializeToString,
            ),
            'TasksInterface': grpc.stream_stream_rpc_method_handler(
                    servicer.TasksInterface,
                    request_deserializer=grpc__pb_dot_manager__grpc__server__pb2.TasksInterfaceRequest.FromString,
                    response_serializer=grpc__pb_dot_manager__grpc__server__pb2.TasksInterfaceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'manager_grpc_server.GrpcServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GrpcServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdateAgentStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/manager_grpc_server.GrpcServer/UpdateAgentStatus',
            grpc__pb_dot_manager__grpc__server__pb2.UpdateAgentStatusRequest.SerializeToString,
            grpc__pb_dot_manager__grpc__server__pb2.UpdateAgentStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GatherInstalledPackages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/manager_grpc_server.GrpcServer/GatherInstalledPackages',
            grpc__pb_dot_manager__grpc__server__pb2.GatherInstalledPackagesRequest.SerializeToString,
            grpc__pb_dot_manager__grpc__server__pb2.GatherInstalledPackagesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RunScaChecks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/manager_grpc_server.GrpcServer/RunScaChecks',
            grpc__pb_dot_manager__grpc__server__pb2.RunScaChecksRequest.SerializeToString,
            grpc__pb_dot_manager__grpc__server__pb2.RunScaChecksResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TasksInterface(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/manager_grpc_server.GrpcServer/TasksInterface',
            grpc__pb_dot_manager__grpc__server__pb2.TasksInterfaceRequest.SerializeToString,
            grpc__pb_dot_manager__grpc__server__pb2.TasksInterfaceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
